{
 "title": "Load Balancer Example",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Service 1",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "api_count{instance=\"service1:8080\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Service 2",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "api_count{instance=\"service2:8080\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Service 3",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "api_count{instance=\"service3:8080\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Service 4",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "api_count{instance=\"service4:8080\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 8 },
   "targets": [
    { "expr": "api_count", "legendFormat": "__auto" }
   ]
  }
 ]
}